services:

  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bigsauto-main

    ports:
      - "${PORT}:8000"
    # command: >
    #   bash -c "alembic upgrade head && gunicorn src.main:app --workers 1 
    #   --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    command: >
      bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./.env
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - bigsauto_net

  mongodb:
    image: mongo:latest
    container_name: bigsauto-mongodb
    ports:
      - "27017:27017"
    # env_file:
    #   - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bigsauto_net

volumes:
  mongo_data:

networks:
  bigsauto_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16